-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 17:49:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`USUARIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(150) NULL,
  `email` VARCHAR(250) NOT NULL,
  `clave` VARCHAR(255) NULL,
  `tipo` ENUM("registrado", "invitado") NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`PEDIDO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `precioTotal` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idUsuario_idx` (`idUsuario` ASC),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `proyecto`.`USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`ZAPATILLA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`ZAPATILLA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `precio` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`PEDIDO_ZAPATILLAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`PEDIDO_ZAPATILLAS` (
  `idPedido` INT NOT NULL,
  `idZapatilla` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  UNIQUE INDEX `idPedido_UNIQUE` (`idPedido` ASC),
  UNIQUE INDEX `idZapatilla_UNIQUE` (`idZapatilla` ASC),
  PRIMARY KEY (`idPedido`, `idZapatilla`),
  CONSTRAINT `idPedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `proyecto`.`PEDIDO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idZapatilla`
    FOREIGN KEY (`idZapatilla`)
    REFERENCES `proyecto`.`ZAPATILLA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
